'use client'
import { ListItem } from '@/components/ListItem';
import { RespCategory } from '@/interface/todo';
import type { Metadata } from 'next'
import Link from 'next/link';
import { useQuery } from 'react-query';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
  
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {

    const { isLoading, error, data } = useQuery<RespCategory>('listCategories', () =>
      fetch('http://localhost:8080/api/v1/category/').then(res =>
        res.json()
      )
    )

    console.log(data);
    

    return (
      <main className="min-h-screen flex flex-row gap-3">
         
        <aside className="flex flex-col w-1/2 gap-5 p-2">

          <h2 className="text-xl ">List Category</h2>

          <ul className="flex flex-col gap-2 max-h-[500px] overflow-auto">
            {
              isLoading
              ? <span>Loading...</span>
              : data?.data.map( category => (
                <ListItem key={category.id_category} id={category.id_category} name={category.name_category} query='category'  />    
              ))
            }
          </ul>
       
          
        </aside>
        
        {children}

      </main>
    )
  }