// Generated by https://quicktype.io

export interface RespTodo {
    data:    Todo[];
    message: string;
    status:  boolean;
}

export interface RespTodoById {
    data:    Todo;
    message: string;
    status:  boolean;
}

export interface RespCategory {
    data:    Category[];
    message: string;
    status:  boolean;
}

export interface RespCategoryById {
    data:    Category;
    message: string;
    status:  boolean;
}

export interface Todo {
    id_todo?:    number;
    name_todo:  string;
    create_at?:  string;
    categories: Category[];
}



export interface Category {
    id_category?:   number;
    name_category: string;
    color:         string;
}
