'use client'
import { ListItem } from '@/components/ListItem';
import { RespTodo } from '@/interface/todo';
import type { Metadata } from 'next'
import Link from 'next/link';
import { useQuery } from 'react-query';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
  
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {

    const { isLoading, error, data } = useQuery<RespTodo>('listTodos', () =>
      fetch('http://localhost:8080/api/v1/todo/').then(res =>
        res.json()
      )
    )

    console.log(data);
    
  
    return (
      <main className="min-h-screen flex flex-row gap-3">
         
        <aside className="flex flex-col w-1/2 gap-5 p-2">

          <h2 className="text-xl ">List Todos</h2>

          <ul className="flex flex-col gap-2">
            {
              isLoading
              ? <span>Loading...</span>
              :
              data?.data.map( todo => (
                <ListItem key={todo.id_todo} id={todo.id_todo!} name={todo.name_todo} query='todo'  />  
              ))
            }
          </ul>

        </aside>
        
        {children}

      </main>
    )
  }